Add MySQL dependency.

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=mysqlDependency]
----

Create a database named `minions`.
In `application.yml` configure just the default datasource to point to this database.
The schema of this database will be generated by Hibernate because of the configuration `dbCreate: update`. The dataSource of each
 user of the application will be configured dynamically and inherit from the default one.

Domain classes dealing with security `User`, `UserRole`, `Role` are mapped to this default dataSource.

[source,groovy]
.grails-app/conf/application.yml
----
include::{sourceDir}/grails-app/conf/application.yml[tag=defaultDatasource]
----

<1> Configure these settings according to your MySQL installation.


Change Multi-Tenancy mode to DATABASE

[source,groovy]
.grails-app/conf/application.yml
----
include::{sourceDir}/grails-app/conf/application.yml[tag=multiTenancyConfiguration]
----

<1> Define Multi-Tenancy mode as `DATABASE`
<2> Set the Tenant Resolver class to a custom class which you wrote in the http://guides.grails.org/grails-custom-security-tenant-resolver/guide/index.html[Custom Tenant Resolver by JWT] guide.